# name: CI / CD

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push for the main branch
#   push:
#     branches: [ master ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
  
# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   AWS_DEFAULT_REGION: 'us-east-1'

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Use Node.js 12.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12.x
#     - name: Install dependencies blog
#       run: |
#         cd blog/
#         aws s3 sync /blog s3://${{ secrets.AWS_S3_BUCKET_NAME }}/blog --acl public-read --delete --cache-control max-age=604800
#     - name: Install dependencies blog
#       run: |
#         cd privacidade/
#         aws s3 sync /privacidade s3://${{ secrets.AWS_S3_BUCKET_NAME }}/privacidade --acl public-read --delete --cache-control max-age=604800
#     # - name: Install dependencies
#     #   run: yarn
#     # - name: "Build"
#     #   run: yarn html-minify
#     # - name: "Deploy to AWS S3"
#     #   run: aws s3 sync /blog s3://${{ secrets.AWS_S3_BUCKET_NAME }}/blog --acl public-read --delete --cache-control max-age=604800
#     - name: "Create AWS Cloudfront Invalidation"
#       run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude 'ferramentas/*' 
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
        SOURCE_DIR: './'      # optional: defaults to entire repository
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
        PATHS: "/*"
        AWS_REGION: "us-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
